### ISSUE TITLE
Support for https://youtu.be/

### ISSUE THREAD

**Issue by bensinclair** [w8tcha/CKEditor-oEmbed-Plugin#85]
Is it possible to add support for shortened YouTube URLs?

E.g: https://youtu.be/la-HOcfWFb4

**Comment by mikhoul** [comment]
@bensinclair   Hi,

I'm not the dev of the plugin but I was looking for an embed plugin for CK and found a solution for your issue:

Here is a solution:
1) Go inside the plugin folder oembed -> libs -> jquery.oembed.min.js
2) Do a search and replace "youtu.be " to ""
3) Save it, then it should be work

Basically there is a variable d="aaa bbb ccc ddd ...".split(" "); which store some invalid urls. They will be used for the if case few lines below in order to separate them out. However, youtu.be is a valid url which already handle by OEmbedProvider "youtube" using "youtu\\.be/[\\w-]+", so it should be removed from that variable d.

**Comment by bensinclair** [comment]
Just read that this plugin is no longer supported. I've just switched to http://ckeditor.com/addon/embed and http://ckeditor.com/addon/autoembed
